### PR TITLE
Hopefully a fix for #79

### PR DESCRIPTION
**Pull request by Austinb**
Compile fix for compile 1.11.2.  Still requires #77

### CODE REVIEW

**Comment by jons** [comment]
you should really just install `libssl-dev`, run configure again, and the error ought to go away when you build.

**Comment by harishalwala** [comment]
This version still does not solve the issue.
I am trying to add upload module with nginx 1.11.3. I have taken latest committed file ngx_http_upload_module.c
it throws following compilation errors.
objs/addon/takenFromGitHub/ngx_http_upload_module.o: In function `ngx_http_upload_flush_output_buffer':
/tmp/takenFromGitHub//ngx_http_upload_module.c:1623: undefined reference to `MD5_Update'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1626: undefined reference to `SHA1_Update'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1629: undefined reference to `SHA256_Update'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1632: undefined reference to `SHA512_Update'
objs/addon/takenFromGitHub/ngx_http_upload_module.o: In function `ngx_http_upload_finish_handler':
/tmp/takenFromGitHub//ngx_http_upload_module.c:1455: undefined reference to `MD5_Final'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1458: undefined reference to `SHA1_Final'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1461: undefined reference to `SHA256_Final'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1464: undefined reference to `SHA512_Final'
objs/addon/takenFromGitHub/ngx_http_upload_module.o: In function `ngx_http_upload_start_handler':
/tmp/takenFromGitHub//ngx_http_upload_module.c:1356: undefined reference to `MD5_Init'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1359: undefined reference to `SHA1_Init'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1362: undefined reference to `SHA256_Init'
/tmp/takenFromGitHub//ngx_http_upload_module.c:1365: undefined reference to `SHA512_Init'
collect2: error: ld returned 1 exit status

**Comment by Austinb** [comment]
@jons Is that ubuntu?  I am using centos 6.8 as my main test platform as that is what my production systems that use this module run on.  I have openssl-devel installed. 
```
Installed Packages
openssl.x86_64                                                                                              1.0.1e-48.el6_8.3                                                                                             @updates
openssl-devel.x86_64                                                                                        1.0.1e-48.el6_8.3                                                                                             @updates
```

Using nginx 1.11.5 release

Module install:
```bash
$ git clone https://github.com/vkholodkov/nginx-upload-module.git /root/src/nginx-upload-module
$ cd /root/src/nginx-upload-module; git checkout 2.2; git pull
```

Configure which works fine:
```bash
./configure --prefix=/usr --user=nginx --group=nginx {lots of other options}  --add-module=/root/src/nginx-upload-module
```

Compile:
```bash
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules \
                -o objs/addon/nginx-upload-module/ngx_http_upload_module.o \
                /root/src/nginx-upload-module/ngx_http_upload_module.c
/root/src/nginx-upload-module/ngx_http_upload_module.c:14:17: error: md5.h: No such file or directory
/root/src/nginx-upload-module/ngx_http_upload_module.c:26:17: error: sha.h: No such file or directory
/root/src/nginx-upload-module/ngx_http_upload_module.c:169: error: expected specifier-qualifier-list before ‘MD5_CTX’
cc1: warnings being treated as errors
/root/src/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_start_handler’:
/root/src/nginx-upload-module/ngx_http_upload_module.c:1366: error: implicit declaration of function ‘MD5Init’
/root/src/nginx-upload-module/ngx_http_upload_module.c:1366: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5’
/root/src/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_finish_handler’:
/root/src/nginx-upload-module/ngx_http_upload_module.c:1465: error: implicit declaration of function ‘MD5Final’
/root/src/nginx-upload-module/ngx_http_upload_module.c:1465: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5_digest’
/root/src/nginx-upload-module/ngx_http_upload_module.c:1465: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5’
/root/src/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_flush_output_buffer’:
/root/src/nginx-upload-module/ngx_http_upload_module.c:1633: error: implicit declaration of function ‘MD5Update’
/root/src/nginx-upload-module/ngx_http_upload_module.c:1633: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5’
/root/src/nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_md5_variable’:
/root/src/nginx-upload-module/ngx_http_upload_module.c:2295: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5_digest’
/root/src/nginx-upload-module/ngx_http_upload_module.c:2295: error: ‘MD5_DIGEST_LENGTH’ undeclared (first use in this function)
/root/src/nginx-upload-module/ngx_http_upload_module.c:2295: error: (Each undeclared identifier is reported only once
/root/src/nginx-upload-module/ngx_http_upload_module.c:2295: error: for each function it appears in.)
/root/src/nginx-upload-module/ngx_http_upload_module.c:2301: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5_digest’
/root/src/nginx-upload-module/ngx_http_upload_module.c:2302: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5_digest’
/root/src/nginx-upload-module/ngx_http_upload_module.c:2305: error: ‘ngx_http_upload_md5_ctx_t’ has no member named ‘md5_digest’
make[1]: *** [objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/root/nginx-1.11.5'
make: *** [build] Error 2
```

If I change to my branch which has this pull request and using the same configure call it compiles fine. 
```bash
$ git clone https://github.com/Austinb/nginx-upload-module.git /root/src/nginx-upload-module
$ cd /root/src/nginx-upload-module; git checkout 2.2; git pull
```

Are you using a specific configure switch that I am missing?

On a side note I did not have to do #77 this time it to get it to compile like before when using vkholodko's 2.2 branch.  Not entirely sure why though...

**Comment by jons** [comment]
yes: ubuntu 16.04 LTS, but nginx source 1.10.1 actually. i suppose a regression was introduced where configure is not doing its job correctly? here's the command and the relevant output in my situation.
```
$ LUAJIT_LIB=/path/to/luajit/lib \
  LUAJIT_INC=/path/to/luajit/include/luajit-2.0 \
  ./configure \
    --prefix=/path/to/nginx \
    --with-ld-opt="-Wl,-rpath,/usr/local/lib" \
    --add-module=/path/to/ext/ngx_devel_kit-0.3.0 \
    --add-module=/path/to/ext/lua-nginx-module-0.10.6

...
checking for md5 in system md library ... not found
checking for md5 in system md5 library ... not found
checking for md5 in system OpenSSL crypto library ... found
checking for sha1 in system md library ... not found
checking for sha1 in system OpenSSL crypto library ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using system PCRE library
  + OpenSSL library is not used
  + md5: using system crypto library
  + sha1: using system crypto library
  + using system zlib library
```

curious output to be sure, but it does compile and run fine.

**Comment by Austinb** [comment]
@jons That makes sense.  The issue showed up in 1.11.2 due to removal of of the switches that include the ssl libraries needed.  See #79 and my comment from July 18, 2016 for more info on what changed. 

From the http://nginx.org/en/CHANGES file it this this entry that caused this module to break when compiling
```
Changes with nginx 1.11.2                                        05 Jul 2016

    *) Change: now nginx always uses internal MD5 and SHA1 implementations;
       the --with-md5 and --with-sha1 configure options were canceled.
```

**Comment by Neptunao** [comment]
Hey guys, any progress on this one?

**Comment by antonbarinov** [comment]
@Neptunao yes, check my PR - https://github.com/vkholodkov/nginx-upload-module/pull/88
I build nginx 11.7 with this module without problems.

**Comment by Austinb** [comment]
@Neptunao I have a branch that will compile against nginx 1.11.7.  You can find it at https://github.com/Austinb/nginx-upload-module just make sure to continue to use the 2.2 branch.  I imagine that this project is no longer being maintained by the owner.  I wish the owner @vkholodkov would give it to someone who can continue to maintain it and if nothing else merge in necessary fixes.  There are still some other issues outstanding that should be merged into this project.

**Comment by matthew-l-weber** [comment]
This pull didn't completely resolve the issue.  I've started https://github.com/vkholodkov/nginx-upload-module/pull/93  with a new openssl dependency.

**Comment by Austinb** [comment]
This has been superseded by #88.  As of now use the 2.255 branch and it should compile properly.

**Pull request closed without merging**
