### PR TITLE
work with latest nginx versions

### PR DESCRIPTION
**Pull request by antonbarinov**
work with latest nginx versions

### CODE REVIEW

**Comment by vkholodkov** [comment]
I cannot verify this at the moment, if someone can provide 3 independent votes that it works, I'll gladly merge this.

**Comment by Austinb** [comment]
This is the same as PR #77.  #77 does work to allow the module to compile in 1.9+

**Comment by fabianbuettner** [comment]
@Austinb no it is not the same, because in PR #88   a lot of changes were made in ngx_http_upload_module.c.

@vkholodkov I am currently using PR #88 with the jQuery File Upload plugin for file upload.
However, I removed the OpenSSL dependency because i don't have OpenSSL on my embedded device. That's why i cannot confirm if the checksums are correct. But file upload works. So +1 from me.

**Comment by Austinb** [comment]
@fabianbuettner I apologize I did not see all of the c file changes.  I just looked at the config file changes  which are the same as #77, I overlook the c file.  The commit message is not very detailed but there a lot of changes. I see the openssl changes due to nginx removing their support (#80) but what do all of the other changes do? I see additional hash functions and what appears to be resume support. What else?

I will pull it and test it on my local but I am curious and I am sure others are as well as to what all these changes do.  Any fix for HTTP/2 by chance?

**Comment by Austinb** [comment]
I have been running this patch locally for 5 days without issue.  Unable to test the http2 stuff locally due to certificate issues.  Any word on http2 in this patch?

As from me the patch doesn't break any thing that I can tell using plupload.  So I give +1.

**Comment by borntorun** [comment]
Can you give your compilation commands and list of dependencies? I'm trying to install the upload module in nginx/1.11.13 running on a container [with this docker hub image](https://github.com/nginxinc/docker-nginx/blob/0c7611139f2ce7c5a6b1febbfd5b436c8c7d2d53/mainline/jessie/Dockerfile) and I'm getting errors on make:

```
bjs/addon/nginx-upload-module-2.255/ngx_http_upload_module.o: In function `ngx_http_upload_flush_output_buffer':
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1625: undefined reference to `MD5_Update'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1628: undefined reference to `SHA1_Update'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1631: undefined reference to `SHA256_Update'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1634: undefined reference to `SHA512_Update'
objs/addon/nginx-upload-module-2.255/ngx_http_upload_module.o: In function `ngx_http_upload_finish_handler':
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1457: undefined reference to `MD5_Final'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1460: undefined reference to `SHA1_Final'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1463: undefined reference to `SHA256_Final'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1466: undefined reference to `SHA512_Final'
objs/addon/nginx-upload-module-2.255/ngx_http_upload_module.o: In function `ngx_http_upload_start_handler':
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1358: undefined reference to `MD5_Init'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1361: undefined reference to `SHA1_Init'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1364: undefined reference to `SHA256_Init'
/tmp/nginx-upload-module-2.255/ngx_http_upload_module.c:1367: undefined reference to `SHA512_Init'
collect2: error: ld returned 1 exit status
objs/Makefile:227: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '/tmp/nginx-1.11.3'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by agilethomas** [comment]
+1 for this patch.

I compiled it into nginx 1.10.3 (for use on Ubuntu 16.04). We don't need SSL support (we terminate at an AWS ELB) but I had to include the ssl module for it to compile. Other modules I included were PCRE, ZLib, and upload-progress-module.

This is my configure command:

./configure --add-module=../nginx-upload-progress-module \
--add-module=../nginx-upload-module \
--with-pcre=../pcre-8.40 \
--with-zlib=../zlib-1.2.11 \
--conf-path=/etc/nginx/nginx.conf \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/lock/nginx.lock \
--http-log-path=/var/log/nginx/access.log \
--http-client-body-temp-path=/var/lib/nginx/body \
--http-proxy-temp-path=/var/lib/nginx/proxy \
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
--with-http_gzip_static_module \
--prefix=/usr/ \
--with-http_ssl_module

**Comment by cbj4074** [comment]
@vkholodkov Thank you for merging this patch! And thank you @Austinb and @fabianbuettner .

I'm able to compile without issue and will be putting this through the paces in the next couple of days. I'll report any unexpected findings, even though the change has been merged.

**Pull request merged**
